ALTER PROC FI_SP_ConsCliente
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT	ID, 
				NOME, 
				SOBRENOME, 
				NACIONALIDADE, 
				CEP, 
				ESTADO, 
				CIDADE, 
				LOGRADOURO, 
				EMAIL, 
				TELEFONE, 
				CPF 
		FROM CLIENTES WITH(NOLOCK)
	ELSE
		SELECT	ID, 
				NOME, 
				SOBRENOME, 
				NACIONALIDADE, 
				CEP, 
				ESTADO, 
				CIDADE, 
				LOGRADOURO, 
				EMAIL, 
				TELEFONE, 
				CPF 
		FROM CLIENTES WITH(NOLOCK) WHERE ID = @ID
END